/*
 * fanet-scenario.cc -- NS-3 scenario matching Table 3 of the manuscript.
 * N UAVs (random waypoint, no pause) send CBR/UDP to one base station at the area centre.
 * Prints ONE CSV line to stdout:
 *   protocol,nUav,vmax,rate,run,tx,rx,pdr,delay_ms,thr_kbps,ctrl,nrl
 *
 * Copy to  <ns-3 dir>/scratch/fanet-scenario.cc  and build with  ./ns3 build
 * Tested API level: ns-3.38 ... ns-3.42 (WIFI_STANDARD_80211b, YansWifiPhyHelper without Default()).
 *
 * The include block and MakeRouting() are generated from src/<module>/helper by setup_nbq_project.sh.
 */
#include "ns3/applications-module.h"
#include "ns3/core-module.h"
#include "ns3/flow-monitor-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/network-module.h"
#include "ns3/wifi-module.h"

// ===== protocol module: QMAODV =====
#include "ns3/qmaodv-module.h"

#include <iostream>
#include <memory>
#include <sstream>
#include <utility>
#include <vector>

using namespace ns3;

// ---------- routing-control counter: every IPv4 transmission of an AODV-family packet (UDP 654)
static uint64_t g_ctrlTx = 0;
static const uint16_t AODV_PORT = 654;

static void
Ipv4TxTrace(Ptr<const Packet> p, Ptr<Ipv4>, uint32_t)
{
    Ptr<Packet> c = p->Copy();
    Ipv4Header ip;
    if (c->RemoveHeader(ip) == 0 || ip.GetProtocol() != UdpL4Protocol::PROT_NUMBER)
        return;
    UdpHeader udp;
    c->RemoveHeader(udp);
    if (udp.GetDestinationPort() == AODV_PORT || udp.GetSourcePort() == AODV_PORT)
        g_ctrlTx++;
}

// ---------- routing attributes: "Name=Value;Name2=Value2" -> helper.Set(Name, StringValue(Value))
using AttrList = std::vector<std::pair<std::string, std::string>>;

static AttrList
ParseAttrs(const std::string& s)
{
    AttrList out;
    std::stringstream ss(s);
    std::string item;
    while (std::getline(ss, item, ';'))
    {
        auto eq = item.find('=');
        if (eq != std::string::npos && eq > 0)
            out.emplace_back(item.substr(0, eq), item.substr(eq + 1));
    }
    return out;
}

template <class H>
static std::unique_ptr<Ipv4RoutingHelper>
Make(const AttrList& attrs)
{
    auto h = std::make_unique<H>();
    for (const auto& kv : attrs)
        h->Set(kv.first, StringValue(kv.second));
    return h;
}

// ---------- protocol factory (generated by setup_nbq_project.sh)
static std::unique_ptr<Ipv4RoutingHelper>
MakeRouting(const std::string& proto, const AttrList& attrs)
{
    if (proto == "QMAODV")
        return Make<QmaodvHelper>(attrs);
    NS_FATAL_ERROR("Unknown protocol: " << proto);
    return nullptr;
}

int
main(int argc, char* argv[])
{
    std::string proto = "AODV";
    uint32_t nUav = 20, run = 1;
    double area = 1000.0, range = 250.0, vmin = 5.0, vmax = 20.0;
    double rate = 4.0, simTime = 200.0;
    uint32_t pktSize = 512;
    std::string routingAttrs = "";

    CommandLine cmd(__FILE__);
    cmd.AddValue("protocol", "AODV|AOMDV|PMAODV|QMAODV|SA-QMAODV|NBQ-MAODV", proto);
    cmd.AddValue("nUav", "number of UAVs", nUav);
    cmd.AddValue("run", "RNG run number (seed)", run);
    cmd.AddValue("area", "side of the square area (m)", area);
    cmd.AddValue("range", "radio range (m)", range);
    cmd.AddValue("vmin", "min speed (m/s)", vmin);
    cmd.AddValue("vmax", "max speed (m/s)", vmax);
    cmd.AddValue("rate", "packets/s per UAV", rate);
    cmd.AddValue("pktSize", "payload bytes", pktSize);
    cmd.AddValue("simTime", "simulation time (s)", simTime);
    cmd.AddValue("routingAttrs", "routing attributes, e.g. \"MaxPaths=3;AdaptiveEpsilon=false\"", routingAttrs);
    cmd.Parse(argc, argv);

    RngSeedManager::SetSeed(12345);
    RngSeedManager::SetRun(run);

    NodeContainer uavs, bs, all;
    uavs.Create(nUav);
    bs.Create(1);
    all.Add(uavs);
    all.Add(bs);

    // ---------- mobility (common random numbers: fixed stream indices)
    std::ostringstream u;
    u << "ns3::UniformRandomVariable[Min=0.0|Max=" << area << "]";
    ObjectFactory pf;
    pf.SetTypeId("ns3::RandomRectanglePositionAllocator");
    pf.Set("X", StringValue(u.str()));
    pf.Set("Y", StringValue(u.str()));
    Ptr<PositionAllocator> pa = pf.Create()->GetObject<PositionAllocator>();
    pa->AssignStreams(1000);
    std::ostringstream sp;
    sp << "ns3::UniformRandomVariable[Min=" << vmin << "|Max=" << vmax << "]";
    MobilityHelper mob;
    mob.SetPositionAllocator(pa);
    mob.SetMobilityModel("ns3::RandomWaypointMobilityModel",
                         "Speed", StringValue(sp.str()),
                         "Pause", StringValue("ns3::ConstantRandomVariable[Constant=0.0]"),
                         "PositionAllocator", PointerValue(pa));
    mob.Install(uavs);
    mob.AssignStreams(uavs, 2000);
    MobilityHelper fixed;
    fixed.SetMobilityModel("ns3::ConstantPositionMobilityModel");
    fixed.Install(bs);
    bs.Get(0)->GetObject<MobilityModel>()->SetPosition(Vector(area / 2, area / 2, 0));

    // ---------- 802.11b ad hoc, 2 Mbit/s, range-limited channel
    WifiHelper wifi;
    wifi.SetStandard(WIFI_STANDARD_80211b);
    wifi.SetRemoteStationManager("ns3::ConstantRateWifiManager",
                                 "DataMode", StringValue("DsssRate2Mbps"),
                                 "ControlMode", StringValue("DsssRate1Mbps"));
    YansWifiChannelHelper ch;
    ch.SetPropagationDelay("ns3::ConstantSpeedPropagationDelayModel");
    ch.AddPropagationLoss("ns3::RangePropagationLossModel", "MaxRange", DoubleValue(range));
    YansWifiPhyHelper phy;
    phy.SetChannel(ch.Create());
    WifiMacHelper mac;
    mac.SetType("ns3::AdhocWifiMac");
    NetDeviceContainer dev = wifi.Install(phy, mac, all);

    // ---------- routing + IP
    auto routing = MakeRouting(proto, ParseAttrs(routingAttrs));
    InternetStackHelper stack;
    stack.SetRoutingHelper(*routing);
    stack.Install(all);
    Ipv4AddressHelper addr("10.1.0.0", "255.255.0.0");
    Ipv4InterfaceContainer ifs = addr.Assign(dev);
    Ipv4Address bsAddr = ifs.GetAddress(nUav);

    // ---------- traffic: every UAV -> base station, CBR over UDP
    const uint16_t port = 9;
    UdpServerHelper server(port);
    ApplicationContainer sa = server.Install(bs.Get(0));
    sa.Start(Seconds(0.0));
    sa.Stop(Seconds(simTime));
    Ptr<UniformRandomVariable> st = CreateObject<UniformRandomVariable>();
    st->SetStream(3000);
    for (uint32_t i = 0; i < nUav; ++i)
    {
        UdpClientHelper client(bsAddr, port);
        client.SetAttribute("Interval", TimeValue(Seconds(1.0 / rate)));
        client.SetAttribute("PacketSize", UintegerValue(pktSize));
        client.SetAttribute("MaxPackets", UintegerValue(4294967295u));
        ApplicationContainer ca = client.Install(uavs.Get(i));
        ca.Start(Seconds(1.0 + st->GetValue(0.0, 1.0 / rate)));
        ca.Stop(Seconds(simTime));
    }

    Config::ConnectWithoutContext("/NodeList/*/$ns3::Ipv4L3Protocol/Tx", MakeCallback(&Ipv4TxTrace));

    FlowMonitorHelper fmh;
    Ptr<FlowMonitor> fm = fmh.InstallAll();

    Simulator::Stop(Seconds(simTime + 1.0));
    Simulator::Run();

    // ---------- metrics (data flows towards the base station only)
    fm->CheckForLostPackets();
    auto cls = DynamicCast<Ipv4FlowClassifier>(fmh.GetClassifier());
    uint64_t tx = 0, rx = 0, rxBytes = 0;
    double delaySum = 0.0;
    for (const auto& kv : fm->GetFlowStats())
    {
        Ipv4FlowClassifier::FiveTuple t = cls->FindFlow(kv.first);
        if (t.destinationAddress != bsAddr || t.destinationPort != port)
            continue;
        tx += kv.second.txPackets;
        rx += kv.second.rxPackets;
        rxBytes += kv.second.rxBytes;
        delaySum += kv.second.delaySum.GetSeconds();
    }
    double pdr = tx ? 100.0 * rx / tx : 0.0;
    double delayMs = rx ? 1000.0 * delaySum / rx : 0.0;
    double thr = rxBytes * 8.0 / simTime / 1000.0;
    double nrl = rx ? double(g_ctrlTx) / rx : 0.0;

    std::cout << proto << "," << nUav << "," << vmax << "," << rate << "," << run << "," << tx << ","
              << rx << "," << pdr << "," << delayMs << "," << thr << "," << g_ctrlTx << "," << nrl
              << std::endl;

    Simulator::Destroy();
    return 0;
}
