/*
 * fanet-scenario.cc -- NS-3 scenario matching Table 3 of the manuscript.
 * N UAVs (random waypoint, no pause) send CBR/UDP to one base station at the area centre.
 * Prints ONE CSV line to stdout:
 *   protocol,nUav,vmax,rate,run,tx,rx,pdr,delay_ms,thr_kbps,ctrl,nrl
 *
 * Copy to  <ns-3 dir>/scratch/fanet-scenario.cc  and build with  ./ns3 build
 * Tested API level: ns-3.38 ... ns-3.42 (WIFI_STANDARD_80211b, YansWifiPhyHelper without Default()).
 *
 * The include block and MakeRouting() are generated from src/<module>/helper by setup_nbq_project.sh.
 */
#include "ns3/applications-module.h"
#include "ns3/core-module.h"
#include "ns3/flow-monitor-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/network-module.h"
#include "ns3/wifi-module.h"
#include "ns3/energy-module.h"

// ===== protocol module: NBQ-MAODV =====
#include "ns3/nbqmaodv-module.h"

#include "fanet-channel.h" // STEP10c

#include <iostream>
#include <memory>
#include <sstream>
#include <utility>
#include <vector>

using namespace ns3;

// ---------- routing-control counter: every IPv4 transmission of an AODV-family packet (UDP 654)
static uint64_t g_ctrlTx = 0;
static const uint16_t AODV_PORT = 654;

static void
Ipv4TxTrace(Ptr<const Packet> p, Ptr<Ipv4>, uint32_t)
{
    Ptr<Packet> c = p->Copy();
    Ipv4Header ip;
    if (c->RemoveHeader(ip) == 0 || ip.GetProtocol() != UdpL4Protocol::PROT_NUMBER)
        return;
    UdpHeader udp;
    c->RemoveHeader(udp);
    if (udp.GetDestinationPort() == AODV_PORT || udp.GetSourcePort() == AODV_PORT)
        g_ctrlTx++;
}

// ---------- routing attributes: "Name=Value;Name2=Value2" -> helper.Set(Name, StringValue(Value))
using AttrList = std::vector<std::pair<std::string, std::string>>;

static AttrList
ParseAttrs(const std::string& s)
{
    AttrList out;
    std::stringstream ss(s);
    std::string item;
    while (std::getline(ss, item, ';'))
    {
        auto eq = item.find('=');
        if (eq != std::string::npos && eq > 0)
            out.emplace_back(item.substr(0, eq), item.substr(eq + 1));
    }
    return out;
}

template <class H>
static std::unique_ptr<Ipv4RoutingHelper>
Make(const AttrList& attrs)
{
    auto h = std::make_unique<H>();
    for (const auto& kv : attrs)
        h->Set(kv.first, StringValue(kv.second));
    return h;
}

// ---------- protocol factory (generated by setup_nbq_project.sh)
static std::unique_ptr<Ipv4RoutingHelper>
MakeRouting(const std::string& proto, const AttrList& attrs)
{
    if (proto == "NBQ-MAODV")
        return Make<NbqmaodvHelper>(attrs);
    NS_FATAL_ERROR("Unknown protocol: " << proto);
    return nullptr;
}

// ---------- STEP8: energy bookkeeping (UAV counted as depleted at the BasicEnergySource
// low-battery threshold, where the WifiRadioEnergyModel switches the PHY off)
static std::vector<Ptr<energy::BasicEnergySource>> g_sources;
static std::vector<bool> g_depleted;
static uint32_t g_nDepleted = 0;
static double g_firstDepletion = -1.0;
static double g_lowThreshold = 0.10;
static double g_sumFracAtDeath = 0.0; // STEP8c: battery fraction when each UAV died
static std::vector<bool> g_phyOffDone;  // STEP8e: PHY actually switched off

// STEP8e: the energy source must not call WifiPhy::SetOffMode() directly: in ns-3.48 this can
// happen in the middle of a reception, and the pending reception event then aborts with
// "Invalid WifiPhy state OFF". PollEnergy() switches the PHY off safely instead.
static void
NoOpDepletion()
{
}
// ---------- STEP8b: energy diagnostics (--energyDebug=1)
static energy::DeviceEnergyModelContainer g_models;
static NetDeviceContainer g_uavDev;

static void
EnergyReport()
{
    double t = Simulator::Now().GetSeconds();
    double sumFrac = 0.0, sumRadio = 0.0;
    uint32_t nOff = 0;
    for (uint32_t i = 0; i < g_models.GetN(); ++i)
    {
        Ptr<energy::BasicEnergySource> src = g_sources[i];
        Ptr<WifiRadioEnergyModel> m = DynamicCast<WifiRadioEnergyModel>(g_models.Get(i));
        Ptr<WifiNetDevice> wd = DynamicCast<WifiNetDevice>(g_uavDev.Get(i));
        double remain = src->GetRemainingEnergy();
        double radioJ = m ? m->GetTotalEnergyConsumption() : -1.0;
        bool off = wd && wd->GetPhy() && wd->GetPhy()->IsStateOff();
        sumFrac += remain / src->GetInitialEnergy();
        sumRadio += radioJ;
        nOff += off ? 1 : 0;
        if (i < 3)
        {
            std::cout << "# ENERGY t=" << t << " uav=" << i << " init=" << src->GetInitialEnergy()
                      << " remainJ=" << remain << " radioJ=" << radioJ
                      << " currentA=" << (m ? m->GetCurrentA() : -1.0)
                      << " state=" << (m ? static_cast<int>(m->GetCurrentState()) : -1)
                      << " phyOff=" << off << std::endl;
        }
    }
    std::cout << "# ENERGY t=" << t << " ALL avgRemainFrac=" << sumFrac / g_models.GetN()
              << " totalRadioJ=" << sumRadio << " phyOffCount=" << nOff
              << " depletedCount=" << g_nDepleted << " avgFracAtDeath="
              << (g_nDepleted ? g_sumFracAtDeath / g_nDepleted : -1.0) << std::endl;
}

static void
PeriodicEnergyReport(double period)
{
    EnergyReport();
    Simulator::Schedule(Seconds(period), &PeriodicEnergyReport, period);
}

static void
PollEnergy(double period)
{
    // STEP8c/8e: a UAV dies when its battery reaches the low-battery threshold (or, with
    // --nsPredictiveOff=1, when ns-3's energy model switches itself to OFF). Death is counted
    // at that instant; the real PHY is switched off at the first poll where it is IDLE, so no
    // transmission/reception is interrupted half-way (avoids an ns-3.48 abort).
    for (size_t i = 0; i < g_sources.size(); ++i)
    {
        Ptr<WifiNetDevice> wd = (i < g_uavDev.GetN()) ? DynamicCast<WifiNetDevice>(g_uavDev.Get(i)) : nullptr;
        if (!g_depleted[i])
        {
            double frac = g_sources[i]->GetRemainingEnergy() / g_sources[i]->GetInitialEnergy();
            Ptr<WifiRadioEnergyModel> m =
                (i < g_models.GetN()) ? DynamicCast<WifiRadioEnergyModel>(g_models.Get(i)) : nullptr;
            bool modelOff = m && m->GetCurrentState() == WifiPhyState::OFF;
            if (modelOff || frac <= g_lowThreshold + 1e-9)
            {
                g_depleted[i] = true;
                ++g_nDepleted;
                g_sumFracAtDeath += frac;
                if (g_firstDepletion < 0)
                    g_firstDepletion = Simulator::Now().GetSeconds();
            }
        }
        if (g_depleted[i] && !g_phyOffDone[i] && wd && wd->GetPhy())
        {
            Ptr<WifiPhy> phy = wd->GetPhy();
            if (phy->IsStateOff())
                g_phyOffDone[i] = true;
            else if (phy->IsStateIdle())
            {
                phy->SetOffMode();
                g_phyOffDone[i] = true;
            }
        }
    }
    Simulator::Schedule(Seconds(period), &PollEnergy, period);
}

int
main(int argc, char* argv[])
{
    std::string proto = "AODV";
    uint32_t nUav = 20, run = 1;
    double area = 1000.0, range = 250.0, vmin = 5.0, vmax = 20.0;
    double rate = 4.0, simTime = 200.0;
    double energyJ = 0.0; // STEP8: 0 = no energy model
    bool energyDebug = false; // STEP8b
    bool nsPredictiveOff = false; // STEP8d: true = original ns-3 predictive switch-to-OFF
    uint32_t pktSize = 512;
    std::string routingAttrs = "";

    CommandLine cmd(__FILE__);
    cmd.AddValue("protocol", "AODV|AOMDV|PMAODV|QMAODV|SA-QMAODV|NBQ-MAODV", proto);
    cmd.AddValue("nUav", "number of UAVs", nUav);
    cmd.AddValue("run", "RNG run number (seed)", run);
    cmd.AddValue("area", "side of the square area (m)", area);
    cmd.AddValue("range", "radio range (m)", range);
    FanetChannelConfig chCfg; // STEP10c
    AddFanetChannelArgs(cmd, chCfg);
    cmd.AddValue("vmin", "min speed (m/s)", vmin);
    cmd.AddValue("vmax", "max speed (m/s)", vmax);
    cmd.AddValue("rate", "packets/s per UAV", rate);
    cmd.AddValue("pktSize", "payload bytes", pktSize);
    cmd.AddValue("simTime", "simulation time (s)", simTime);
    cmd.AddValue("energyJ", "initial energy per UAV in J (0 = no energy model)", energyJ);
    cmd.AddValue("nsPredictiveOff",
                 "STEP8d: keep ns-3's predictive switch-to-OFF of WifiRadioEnergyModel "
                 "(needs the ns3-patches/wifi-radio-energy-model patch)",
                 nsPredictiveOff);
    cmd.AddValue("energyDebug", "STEP8b: print energy diagnostics every 10 s and at the end", energyDebug);
    cmd.AddValue("routingAttrs", "routing attributes, e.g. \"MaxPaths=3;AdaptiveEpsilon=false\"", routingAttrs);
    cmd.Parse(argc, argv);

    RngSeedManager::SetSeed(12345);
    RngSeedManager::SetRun(run);

    NodeContainer uavs, bs, all;
    uavs.Create(nUav);
    bs.Create(1);
    all.Add(uavs);
    all.Add(bs);

    // ---------- mobility (common random numbers: fixed stream indices)
    std::ostringstream u;
    u << "ns3::UniformRandomVariable[Min=0.0|Max=" << area << "]";
    ObjectFactory pf;
    pf.SetTypeId("ns3::RandomRectanglePositionAllocator");
    pf.Set("X", StringValue(u.str()));
    pf.Set("Y", StringValue(u.str()));
    Ptr<PositionAllocator> pa = pf.Create()->GetObject<PositionAllocator>();
    pa->AssignStreams(1000);
    std::ostringstream sp;
    sp << "ns3::UniformRandomVariable[Min=" << vmin << "|Max=" << vmax << "]";
    MobilityHelper mob;
    mob.SetPositionAllocator(pa);
    mob.SetMobilityModel("ns3::RandomWaypointMobilityModel",
                         "Speed", StringValue(sp.str()),
                         "Pause", StringValue("ns3::ConstantRandomVariable[Constant=0.0]"),
                         "PositionAllocator", PointerValue(pa));
    mob.Install(uavs);
    mob.AssignStreams(uavs, 2000);
    MobilityHelper fixed;
    fixed.SetMobilityModel("ns3::ConstantPositionMobilityModel");
    fixed.Install(bs);
    bs.Get(0)->GetObject<MobilityModel>()->SetPosition(Vector(area / 2, area / 2, 0));

    // ---------- 802.11b ad hoc, 2 Mbit/s, range-limited channel
    WifiHelper wifi;
    wifi.SetStandard(WIFI_STANDARD_80211b);
    wifi.SetRemoteStationManager("ns3::ConstantRateWifiManager",
                                 "DataMode", StringValue("DsssRate2Mbps"),
                                 "ControlMode", StringValue("DsssRate1Mbps"));
    YansWifiChannelHelper ch;
    YansWifiPhyHelper phy;
    chCfg.range = range;
    ConfigureFanetChannel(ch, phy, chCfg); // STEP10c: --channel=range (default) | fading
    phy.SetChannel(ch.Create());
    WifiMacHelper mac;
    mac.SetType("ns3::AdhocWifiMac");
    NetDeviceContainer dev = wifi.Install(phy, mac, all);

    // ---------- STEP8: battery + 802.11 radio energy model on every UAV (not on the base station)
    if (energyJ > 0.0)
    {
        BasicEnergySourceHelper batt;
        batt.Set("BasicEnergySourceInitialEnergyJ", DoubleValue(energyJ));
        batt.Set("BasicEnergyLowBatteryThreshold", DoubleValue(g_lowThreshold));
        energy::EnergySourceContainer sources = batt.Install(uavs);
        NetDeviceContainer uavDev;
        for (uint32_t i = 0; i < nUav; ++i)
            uavDev.Add(dev.Get(i));
        WifiRadioEnergyModelHelper radio; // depletion -> WifiPhy::SetOffMode
        // STEP8d: depletion decided by the battery low threshold only (see ns3-patches/)
        radio.Set("PredictiveSwitchToOff", BooleanValue(nsPredictiveOff));
        radio.SetDepletionCallback(MakeCallback(&NoOpDepletion)); // STEP8e
        g_models = radio.Install(uavDev, sources); // STEP8b: keep for diagnostics
        g_uavDev = uavDev;
        if (energyDebug)
            Simulator::Schedule(Seconds(10.0), &PeriodicEnergyReport, 10.0);
        for (uint32_t i = 0; i < sources.GetN(); ++i)
            g_sources.push_back(DynamicCast<energy::BasicEnergySource>(sources.Get(i)));
        g_depleted.assign(g_sources.size(), false);
        g_phyOffDone.assign(g_sources.size(), false); // STEP8e
        Simulator::Schedule(Seconds(0.1), &PollEnergy, 0.1); // STEP8c: 0.1 s
    }

    // ---------- routing + IP
    auto routing = MakeRouting(proto, ParseAttrs(routingAttrs));
    InternetStackHelper stack;
    stack.SetRoutingHelper(*routing);
    stack.Install(all);
    Ipv4AddressHelper addr("10.1.0.0", "255.255.0.0");
    Ipv4InterfaceContainer ifs = addr.Assign(dev);
    Ipv4Address bsAddr = ifs.GetAddress(nUav);

    // ---------- traffic: every UAV -> base station, CBR over UDP
    const uint16_t port = 9;
    UdpServerHelper server(port);
    ApplicationContainer sa = server.Install(bs.Get(0));
    sa.Start(Seconds(0.0));
    sa.Stop(Seconds(simTime));
    Ptr<UniformRandomVariable> st = CreateObject<UniformRandomVariable>();
    st->SetStream(3000);
    for (uint32_t i = 0; i < nUav; ++i)
    {
        UdpClientHelper client(bsAddr, port);
        client.SetAttribute("Interval", TimeValue(Seconds(1.0 / rate)));
        client.SetAttribute("PacketSize", UintegerValue(pktSize));
        client.SetAttribute("MaxPackets", UintegerValue(4294967295u));
        ApplicationContainer ca = client.Install(uavs.Get(i));
        ca.Start(Seconds(1.0 + st->GetValue(0.0, 1.0 / rate)));
        ca.Stop(Seconds(simTime));
    }

    Config::ConnectWithoutContext("/NodeList/*/$ns3::Ipv4L3Protocol/Tx", MakeCallback(&Ipv4TxTrace));

    FlowMonitorHelper fmh;
    Ptr<FlowMonitor> fm = fmh.InstallAll();

    Simulator::Stop(Seconds(simTime + 1.0));
    Simulator::Run();
    if (energyDebug && g_models.GetN() > 0)
        EnergyReport(); // STEP8b: final snapshot (printed before the CSV line)

    // ---------- metrics (data flows towards the base station only)
    fm->CheckForLostPackets();
    auto cls = DynamicCast<Ipv4FlowClassifier>(fmh.GetClassifier());
    uint64_t tx = 0, rx = 0, rxBytes = 0;
    double delaySum = 0.0;
    for (const auto& kv : fm->GetFlowStats())
    {
        Ipv4FlowClassifier::FiveTuple t = cls->FindFlow(kv.first);
        if (t.destinationAddress != bsAddr || t.destinationPort != port)
            continue;
        tx += kv.second.txPackets;
        rx += kv.second.rxPackets;
        rxBytes += kv.second.rxBytes;
        delaySum += kv.second.delaySum.GetSeconds();
    }
    double pdr = tx ? 100.0 * rx / tx : 0.0;
    double delayMs = rx ? 1000.0 * delaySum / rx : 0.0;
    double thr = rxBytes * 8.0 / simTime / 1000.0;
    double nrl = rx ? double(g_ctrlTx) / rx : 0.0;

    std::cout << proto << "," << nUav << "," << vmax << "," << rate << "," << run << "," << tx << ","
              << rx << "," << pdr << "," << delayMs << "," << thr << "," << g_ctrlTx << "," << nrl
              << "," << g_nDepleted << ","
              << (g_firstDepletion < 0 ? simTime : g_firstDepletion) // STEP8: 14 fields
              << std::endl;

    Simulator::Destroy();
    return 0;
}
