"""
split_and_fix.py <ns3_dir> <proj_dir>
 1) Gives every header of src/nbqmaodv a unique include guard (NBQMAODV_<FILE>_H), so it can
    never be skipped because another module (aodv/saqmaodv/...) uses the same guard name.
 2) Splits scratch/fanet-scenario.cc into one scenario per protocol
    (scratch/fanet-scenario-<module>.cc), each including ONLY its own module.
    Baseline modules (aodv, pmaodv, qmaodv, saqmaodv) are not modified.
"""
import glob, os, re, shutil, sys

ns3, proj = sys.argv[1], sys.argv[2]
MODS = {"AODV": "aodv", "PMAODV": "pmaodv", "QMAODV": "qmaodv", "SA-QMAODV": "saqmaodv", "NBQ-MAODV": "nbqmaodv"}

# ---- 1. unique include guards in nbqmaodv
for h in sorted(glob.glob(f"{ns3}/src/nbqmaodv/**/*.h", recursive=True)):
    s = open(h, errors="ignore").read()
    m = re.search(r"^[ \t]*#ifndef[ \t]+(\w+)[ \t]*\r?\n[ \t]*#define[ \t]+\1\b", s, re.M)
    if not m:
        print(f"  (no include guard found in {os.path.basename(h)}, left as is)")
        continue
    old = m.group(1)
    new = "NBQMAODV_" + re.sub(r"\W", "_", os.path.basename(h)).upper()
    if old != new:
        s = re.sub(r"\b%s\b" % re.escape(old), new, s)
        open(h, "w").write(s)
        print(f"  guard {os.path.basename(h):40s} {old} -> {new}")

# ---- 2. one scenario per protocol
src = f"{ns3}/scratch/fanet-scenario.cc"
if not os.path.exists(src):
    sys.exit(f"  {src} not found (already split?)")
s = open(src).read()
case_re = r'    if \(proto == "([^"]+)"\)\n        return Make<(\w+)>\(attrs\);\n'
cases = re.findall(case_re, s)
body = re.sub(case_re, "", s)
body = re.sub(r'#include "ns3/(?:aodv|pmaodv|qmaodv|saqmaodv|nbqmaodv)-module\.h"\n', "", body)
marker = "// ===== protocol modules (generated by setup_nbq_project.sh) =====\n"
assert marker in body and 'NS_FATAL_ERROR("Unknown protocol: "' in body, "unexpected scenario layout"
for name, helper in cases:
    mod = MODS[name]
    t = body.replace(marker, f"// ===== protocol module: {name} =====\n#include \"ns3/{mod}-module.h\"\n")
    t = t.replace('    NS_FATAL_ERROR("Unknown protocol: "',
                  f'    if (proto == "{name}")\n        return Make<{helper}>(attrs);\n'
                  '    NS_FATAL_ERROR("Unknown protocol: "', 1)
    open(f"{ns3}/scratch/fanet-scenario-{mod}.cc", "w").write(t)
    print(f"  scratch/fanet-scenario-{mod}.cc  ({name} -> {helper})")
os.makedirs(f"{proj}/backup", exist_ok=True)
shutil.move(src, f"{proj}/backup/fanet-scenario-all-in-one.cc")
print("  old all-in-one scenario moved to backup/ (no longer built)")
